{ pkgs, coverage }:
let
  # Landing page for the published site. Links are relative to this directory:
  # the site is served from `/<repo>/`, so a `../` prefix escapes the Pages
  # prefix and 404s. The pre-#6136 index was generated by `tree -H . --fromfile`,
  # which emits exactly such `../` links, so every link on it was broken.
  index = pkgs.writeText "index.html" ''
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Motoko build reports</title>
    </head>
    <body>
      <h1>Motoko build reports</h1>
      <ul>
        <li><a href="./coverage/">Coverage report</a> — OCaml coverage of the
        compiler sources (bisect_ppx), from the test suite.</li>
      </ul>
      <p>Regenerated for every <code>master</code> build.</p>
    </body>
    </html>
  '';
in
pkgs.runCommand "report-site" { } ''
  mkdir -p $out
  ln -s ${coverage} $out/coverage
  cp ${index} $out/index.html
''
