version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: '00:00'
      timezone: UTC
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/doc/site"
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: UTC
    groups:
      docs-site:
        patterns:
          - "*"
    open-pull-requests-limit: 5
